version: '3.8'
services:

  eureka-server:
    image: eurekaserver:latest
    build:
      context: ./eureka-server
    ports:
      - "8761:8761"

  class-service:
    image: class-service:latest
    build:
      context: ./class-service
    ports:
      - "8082:8082"
    depends_on:
      - eureka-server
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/

  student-service:
    image: student-service:latest
    build:
      context: ./student-service
    ports:
      - "8081:8081"
    depends_on:
      - class-service
      - eureka-server
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
